# Generated by Django 4.1.5 on 2023-01-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageEdit',
        ),
    ]
